uls_resource.settings:
  type: config_object
  label: 'ULS Resource EAD settings'
  mapping:
    archivesspace_base_uri:
      type: string
      label: 'ArchivesSpace API Endpoint'
      constraints:
        NotBlank:
          message: "Please set ArchivesSpace API uri."
    archivesspace_username:
      type: string
      label: 'ArchivesSpace API Username'
    archivesspace_password:
      type: string
      label: 'ArchivesSpace API Password'
    archivesspace_viewonlineuri:
      type: string
      label: 'Resource Viewonline Prefix'
    archivesspace_readingroomuri:                                      
      type: string 
      label: 'Resource Readingroom Prefix'


